# Generated by Django 2.0.2 on 2018-03-04 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acumen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='level',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='room',
            name='occupants',
            field=models.IntegerField(),
        ),
    ]
