# Generated by Django 2.0.2 on 2018-03-04 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acumen', '0002_auto_20180303_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('eye_color', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='room',
            name='level',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='room',
            name='owner',
            field=models.CharField(max_length=50),
        ),
    ]
