# Generated by Django 2.0.2 on 2018-03-04 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acumen', '0003_auto_20180303_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(default='replaceme', max_length=50),
            preserve_default=False,
        ),
    ]
